import type { Metadata } from "next";
import "./globals.css";
import Header from "sbt/distro/header/Header";


export const metadata: Metadata = {
  title: "OWMC D3",
  description: "D3 data visualisation. Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks =[
    { title: 'About', url: '/about/' },
    { title: 'Charts', url: '/charts/' },
  ];
  const logoLink = {
    title: 'Home',
    url: '/'
  };
  return (
    <html lang="en">
      <body className="font-sans">
        <Header navLinks={navLinks} logoLink={logoLink} />
        <main className="p-5">
          {children}
        </main>
      </body>
    </html>
  );
}
